# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Self-Sufficiency Standard
tagline:          ''
description:      'A 2022 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2022-Self-Sufficiency/"


paginate:         5

# Custom vars
version:          1.0.0

github:           https://github.com/Center-for-Women-s-Welfare/SSS
  repo:           https://github.com/uwescience/DSSG2022-Self-Sufficiency/
